### PR TITLE
CMSC 5733 Assignment 4 Test Pull Request

### PR DESCRIPTION
**Pull request by Manik-Coder**
Created new test cases to check methods and updated the Method for checking the target.

### CODE REVIEW

**Comment by kalkedan** [comment]
looks good !

**Comment by logan-giese** [comment]
Your algorithm for checking the number addition is efficient, clean, and concise.  However, it looks like the formatting for your test code lost its alignment so everything is stuck on the left, making it much harder to read.

**Comment by ericgeil223** [comment]
Output looks a bit busy to me. Other than that looks good and clean.

**Comment by sagarbadu** [comment]
Short and clear. Looks good.

**Pull request closed without merging**
